/* Squeezes */
export const SET_LONG_INTERVAL = 'SET_LONG_INTERVAL';
export const SET_LONG_REPETITIONS = 'SET_LONG_REPETITIONS';
export const SET_SHORT_REPETITIONS = 'SET_SHORT_REPETITIONS';
export const SET_DAILY_SESSIONS = 'SET_DAILY_SESSIONS';
