/* Squeezes */
export const SET_DAILY_SESSIONS = 'SET_DAILY_SESSIONS';
export const SET_LONG_RESULTS = 'SET_LONG_RESULTS';
export const SET_SHORT_RESULTS = 'SET_SHORT_RESULTS';
export const SET_SELECTED_INDEX = 'SET_SELECTED_INDEX';
/* Leakage */
export const GET_LEAKAGE_DATA = 'GET_LEAKAGE_DATA';
export const SET_IN_VOLUME = 'SET_IN_VOLUME';
export const SET_OUT_VOLUME = 'SET_OUT_VOLUME';
/* Insights */
export const GET_LAST_WEEKS_INSIGHT = 'GET_LAST_WEEKS_INSIGHT';
export const LEAK_PERCENT_UPDATED = 'LEAK_PERCENT_UPDATED';
export const SQUEEZE_PERCENT_UPDATED = 'SQUEEZE_PERCENT_UPDATED';
