/* Squeezes */
export const SET_DAILY_SESSIONS = 'SET_DAILY_SESSIONS';
export const SET_LONG_RESULTS = 'SET_LONG_RESULTS';
export const SET_SHORT_RESULTS = 'SET_SHORT_RESULTS';
export const SET_SELECTED_INDEX = 'SET_SELECTED_INDEX';
